### ISSUE TITLE
TooManyRedirects: Exceeded 30 redirects！

### ISSUE THREAD

**Issue by tangxiangru** [shashiongithub/XSum-Dataset#1]
urls left to download: 226711
3.78% [8579/226711]Traceback (most recent call last):
  File "download-bbc-articles.py", line 245, in <module>
    main()
  File "download-bbc-articles.py", line 240, in main
    DownloadMode(urls_file_to_download, missing_urls_file, downloads_dir, args.request_parallelism)
  File "download-bbc-articles.py", line 194, in DownloadMode
    for url, story_html in results:
  File "/root/anaconda3/envs/python2/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by shashiongithub** [comment]
Does the problem remain after running this multiple times? Let me know if it does not work.

**Comment by tangxiangru** [comment]
It is because some urls is dead.By the way, should I delete the missing.txt after one turn was over?

**Comment by shashiongithub** [comment]
No, you should not delete missing.txt. The next iteration downloads urls from missing.txt. Could you give me a few examples from misssing.txt.

**Comment by shashiongithub** [comment]
Thanks! I have updated the code.

I am looking into the download problems. Could you send me an email and we can take the issue there?

**Comment by shashiongithub** [comment]
I have made some changes to the download script. see the README file.

Each URL includes a timestamp (14 letters; year, month, date, hour, minute and second, e.g., 20130206080312) showing when it was stored. By default, it is set to 14 letters. You can lower this to improve your chances to download a BBC article. Every time you rerun the download script, lower the timestamp_exactness (>= 1) to improve the chances of getting missed URLs from the previous step. However, lower the timestamp_exactness value, more time it will take to retrieve the article.

Try this if it improves. Otherwise, drop me an email and see what I can do.

**Comment by bckim92** [comment]
I think we can handle this error by adding following exception handling code somewhere between line 128~140

```
try:
    req = requests.get(url, allow_redirects=True, timeout=timeout)
except requests.exceptions.TooManyRedirects as exc:
    r = exc.response
```
